spring:
  application:
    name: publisher
  datasource:
    url: jdbc:postgresql://postgres-db:5432/distcomp
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    url: jdbc:postgresql://postgres-db:5432/distcomp
    user: postgres
    password: postgres
    default-schema: public
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: notice-consumer-group
  data:
    redis:
      host: redis
      port: 6379
      connect-timeout: 600
server:
  port: 24110
topic:
  name: InTopic

jwt:
  secret: testSecretKey1234567890testSecretKey1234567890
  expiration: 86400000





